### ISSUE TITLE
Dev | Fetch data from JSON / data source

### ISSUE THREAD

**Issue by velram** [velram/bday-wish-bot#4]
**Problem statement** :  Fetch data from JSON / other data source. 

**Approach** : 
1. Currently, proposing to use the JSON file itself for initial phases. 
2. Read the JSON input from the file.  

**Sub-tasks** :

- [ ] Prepare a sample JSON file
- [ ] Query the JSON object with current date
- [ ] Parse the JSON fields and convert it into Toot
